### PR TITLE
Bumped jacoco version to 0.7.5.201505241946

### PR DESCRIPTION
**Pull request by linjer**
There are various bug fixes in upping from version 0.7.1 to patch version 5.

https://github.com/jacoco/jacoco/releases

### CODE REVIEW

**Comment by linjer** [comment]
Is this project still being maintained?

**Comment by linjer** [comment]
Bump.

**Comment by salex89** [comment]
Bump 2.0 ?

**Comment by maxkremer** [comment]
@jmhofer do you have any plan to merge these PRs? Are you still maintaining this project?

**Comment by linjer** [comment]
@salex89 @maxkremer This PR is getting a bit stale. If we're able to get some maintenance going again, we can now upgrade to JaCoCo 0.7.6

**Comment by maxkremer** [comment]
@linjer stale? It's upto date with master and has no confilicts

**Comment by linjer** [comment]
@maxkremer sorry didn't mean it in that sense, but that JaCoCo 0.7.6 has been recently released and this PR is to bump version to 0.7.5. This PR can still be merged but is slightly dated.

**Comment by maxkremer** [comment]
@linjer oh gotcha! yup 0.7.6 would be even better.... question is can we get someone to merge the PR

**Comment by salex89** [comment]
I was even thinking about making a complete fork of this project, and try republishing with a different group id, of course, respecting the original author. The issue is, I don't have almost any knowledge about SBT plugin development, so it would be bodging. Any substantial change would be a probable flop :-) .

**Comment by linjer** [comment]
I can make a fork and maintain it. I just didn't see the value at the time but since this seems like it may be unmaintained I may publish a fork with at a minimum updated jacoco.

**Comment by maxkremer** [comment]
That would be great. Just an FYI I tried with Jacoco 0.7.5 and 0.7.6  - both failed miserably. I don't think its as simple as bumping the jacoco version. There must've been significant changes made in 0.7.5...

**Comment by salex89** [comment]
Yep, versions after 0.7.5 are not compatible with 0.7.4 exec format. One of the reason for updating, at least from my stance, is that the Jenkins Jacoco plugin is also not compatible with this jacoco4sbt. Because of sheer luck, we are stuck with the older Jenkins Jacoco plugin, but at some point this will become an issue again. Not sure what's smart. As far as I hear, same goes for Sonar.

**Comment by linjer** [comment]
@salex89 that would actually be one of the primary reasons why I opened this PR. We've dealt with it just fine though, and presumably others as well. Seems like the need is continuing the grow though. Again I'll look at publishing a fork but I'm pretty swamped for the time being.

**Comment by jmhofer** [comment]
Thanks, and sorry for my looon inactivity!

**Pull request merged**
